### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by brainwane** [FFY00/python-build#10]
Hi! I saw [your note about potentially moving this project to the PyPA](https://discuss.python.org/t/moving-python-build-to-pypa/4390).

I don't see a code of conduct in your top-level directory; I suggest you do something like [what pip did](https://github.com/pypa/pip/#code-of-conduct) and add a line to your README saying that interactions with/within the project are subject to the PyPA Code of Conduct. Or prep that change as a pull request, approve it, and then be ready to merge it if/when the project moves into PyPA.

Thanks!

**Comment by pganssle** [comment]
This was fixed in #11, right?

Closing, but feel free to re-open if there are other open issues.
