### ISSUE TITLE
Add ability to select certain patterns to ignore when copying for isolation

### ISSUE THREAD

**Issue by ofek** [FFY00/python-build#100]
Such as `.tox`, which usually takes a long time to copy on Windows.

Code here: https://github.com/FFY00/python-build/blob/b805ff79227d7d72057068e292ab10af6861fcb6/src/build/env.py#L116

Docs for `ignore` callable kwarg here: https://docs.python.org/3/library/shutil.html#shutil.copytree

**Comment by FFY00** [comment]
Well, that is not available on Python 2, so we would have to do https://github.com/FFY00/python-build/blob/b805ff79227d7d72057068e292ab10af6861fcb6/tests/conftest.py#L56.

But that is private API and I don't think our current usages would have result in a `.tox` a directory being copied. Could you elaborate a bit here?

**Comment by ofek** [comment]
I haven't tested this yet, but I know when pip installs a local path without `-e` it copies everything and whenever I build I used to temporarily move `.tox` to make it much faster.

**Comment by FFY00** [comment]
Ah, I need to add a doctring to the install method, I jusy discussed it yesterday. `install` should receive a sequence of [PEP 508](https://www.python.org/dev/peps/pep-0508) strings, so installing a local path should not happen, if it does work it's implementation detail. Sorry for the trouble.

**Comment by ofek** [comment]
Oh okay, thanks! So for isolation we don't actually copy projects to a temporary directory, we just modify environment variables?

**Comment by FFY00** [comment]
Yes. To build a package via PEP 517 the package code isn't run (by us at least), so it never needs to get installed. What is run is the backend, so we create an isolated environment, install the backend there and call the PEP 517 backend hooks pointing to the location of the package. This was just a quick description, hopefully that made sense to you :blush:

**Comment by ofek** [comment]
Great work, thank you!
