### ISSUE TITLE
Plans/need for an equivalent to pep517.check?

### ISSUE THREAD

**Issue by matthewfeickert** [FFY00/python-build#105]
Hi. I'm coming here from https://github.com/pypa/pep517/issues/91 as it is noted on the checklist that

>  Add a deprecation warning when `pep517.check` is used

Apologies in advance is this is covered in an Issue already and I've failed to find it, but as it isn't mentioned in PR #83, are there plans to also make an [equivalent of `pep517.check` available in the `build` CLI API](https://github.com/scikit-hep/pyhf/issues/1065#issuecomment-692293800)?

Though perhaps there isn't an explicit need for the `check` API (?) given that [`python-build` (and `pep517.build`) seems to perform the equivalent of `pep517.check` during its run](https://github.com/scikit-hep/pyhf/issues/1065#issuecomment-692362772).

**Comment by pganssle** [comment]
I will defer to @FFY00 on this, but my $0.02 is that while some sort of a `--dry-run` or `--check-only` flag isn't the worst thing in the world, it may be hard to communicate exactly what it does. I am not sure "validate your `build-system` table" is what most people would think it does — they may think that it's doing something more extensive, or that it checks existing built artifacts or something.

If we decide something like this is worth including, we'll have to be very careful about the UI.

**Comment by FFY00** [comment]
I think this is a bit out of scope. Perhaps you could try to convince me otherwise by explaining why it is needed.
From a quick look, `pep517.check` seems to actually build the sdist and/or wheel and just delete the directory afterwards. I would say to just replace `pep517.check` with the build command, if you want you don't want the artifacts then remove the output directory.

**Comment by matthewfeickert** [comment]
> I would say to just replace pep517.check with the build command, if you don't want the artifacts then remove the output directory.

@FFY00 This is good enough for me now given my comment above. I was expecting feature parity in the API, though as you say, this isn't really needed perhaps. Thanks!

**Comment by takluyver** [comment]
`pep517.check` does do a tiny bit more than building - e.g. it verifies that the produced packages have the expected extensions and the expected archive formats (zip/tar). It's also trying to have clear & concise error messages when the checks fail, though I don't know if it does a good job of that.

**Comment by FFY00** [comment]
Thanks for clarifying! I still think it's a bit out of scope, if this is indeed a need perhaps there would be a place for an external PEP517 checker package.

**Comment by takluyver** [comment]
Yeah, I think it might make sense to do it as a separate package.

**Comment by FFY00** [comment]
Alright, I am gonna close this then.
