### ISSUE TITLE
Test suite breaks on pypy3.6 - 7.3.2 

### ISSUE THREAD

**Issue by gaborbernat** [FFY00/python-build#123]
It's because of https://foss.heptapod.net/pypy/pypy/-/issues/3321

**Comment by FFY00** [comment]
We can temporarily remove it then.

**Comment by gaborbernat** [comment]
Maybe you meant disable it?

**Comment by FFY00** [comment]
I mean, remove `pypy3` from the run matrix. We can re-add it when the issue is solved.

**Comment by gaborbernat** [comment]
I don't think we need to remove it from the matrix. We need to just mark one tests skipped.

**Comment by FFY00** [comment]
Sure. Do you want to open a PR?

**Comment by gaborbernat** [comment]
Resolved by https://github.com/FFY00/python-build/pull/125
