### ISSUE TITLE
Support `config_settings`

### ISSUE THREAD

**Issue by FFY00** [FFY00/python-build#16]
We should add support to pass `config_settings` to the PEP517 hooks.

I propose the following:
```python
parser.add_argument('--config', '-C', action='append')
```

Allowing users to pass arguments as follows:
```
... -Csomething=value
... -C something=value
... -C 'something with spaces=another value'
```

This is a pretty standard way to pass extra arguments to build systems and I think it would fit here nicely.

cc @gaborbernat

**Comment by gaborbernat** [comment]
We merged this under https://github.com/FFY00/python-build/pull/27
