### ISSUE TITLE
API reference missing in the online documentation

### ISSUE THREAD

**Issue by FFY00** [FFY00/python-build#23]
`sphinx-apidoc` needs to run on the module to generate the API reference. RTD does not support this.

I tried `autoapi.extension` but it does not correctly annotate `__init__` methods.

We will probably have to move the apidoc building step from the makefile to `conf.py`/custom sphinx extension, but I am not happy about this.

**Comment by gaborbernat** [comment]
I have this working with tox and virtualenv, can put in a pr next week with it.

**Comment by gaborbernat** [comment]
@FFY00 what parts do you want to expose publicly? 

> I tried `autoapi.extension` but it does not correctly annotate `__init__` methods.

Can you expand what exactly you think it's not correct?

**Comment by FFY00** [comment]
```python
def __init__(self, something):  # type: (int) -> None
    ...
```

Would document `self` as `int` and would not document `something`'s type.

**Comment by gaborbernat** [comment]
Will take a look later.

**Comment by pradyunsg** [comment]
> ```
> def __init__(self, something):  # type: (int) -> None
> ```

Shouldn't it be:

```py
class Whatever:
    def __init__(self, something):
        # type: (int) -> None
        pass
```

**Comment by FFY00** [comment]
Yes, I supressed the class.

**Comment by EpicWink** [comment]
FYI on this one, you can use custom templates

**templates/package.rst_t**
```rst
{{ pkgname | e | heading }}
{% if subpackages or submodules %}
.. toctree::
{% for docname in (subpackages or []) + (submodules or []) %}
   {{ docname }}
{%- endfor %}
{% endif %}
.. automodule:: {{ pkgname }}
{%- for option in automodule_options %}
   :{{ option }}:
{%- endfor %}
```

**Makefile**
```make
...
TEMPLATEDIR = templates
...
apidoc:
	$(SPHINXGEN) -eTf -t "$(TEMPLATEDIR)" -o "$(SOURCEDIR)" ../src
...
```

**Comment by FFY00** [comment]
This has been fixed but the issue was never closed.

https://python-build.readthedocs.io/en/latest/build.html
