### ISSUE TITLE
Add an entry point?

### ISSUE THREAD

**Issue by pganssle** [FFY00/python-build#3]
I notice that this is invoked with `python -m build`. I think it would be a good idea to add `python-build` or `pybuild` or something of that nature as an entry point.

The reason that I think this is a good idea is that [`pipx`](https://pypi.org/project/pipx/) can only install command line tools that expose entry points, and this is the kind of tool I'd want available via `pipx` (though probably in any production use I'd be running it in a CI job or something that won't go via `pipx`).

**Comment by FFY00** [comment]
Can I expose a custom entry point (not script)? I think I want to avoid the whole script in `PATH` vs custom python installation mess.

**Comment by FFY00** [comment]
Something like

```ini
[pipx]
python-build = build.__main__
```

**Comment by pganssle** [comment]
I don't really know how `pipx` works, but I assume that you must expose an entry point. These entry points are usually generated automatically by the installation script, if that's what you mean.

I would guess that there's no way to make it so that it is both compatible with `pipx` and invoked only by `python -m ...` since `pipx` basically installs everything into separate virtual environments and then adds that's virtualenv's entry point scripts into a directory on your `PATH` (I have no idea how it handles conflicts). If you invoke `python` you immediately have to know *which* `python` you are invoking, so without some probably unseemly shimming going on, I think there would be no way to expose the `build` module without effectively installing `build` as a module into your global Python installation, which is what `pipx` is trying to avoid in the first place.

This is a CLI tool, I don't see a major issue in exposing a CLI endpoint for it and letting end users figure out how they handle whatever various conflicting installation paths they're likely to hit the way they have to with every other Python CLI tool.

**Comment by FFY00** [comment]
Adding a `console_scripts` entrypoint should not be that big of a deal, but something I was trying to avoid.

What I was proposing was declaring a entrypoint just for pipx. The entry points spec allows this: https://packaging.python.org/specifications/entry-points/#file-format

> pipx is a tool to install and run any of these thousands of application-containing packages in a safe, convenient, and reliable way. In a way, it turns Python Package Index (PyPI) into a big app store for Python applications. Not all Python packages have entry points, but many do.

Seems to suggest it only works on `console_scripts`.

Anyway, I'll add a `console_scripts` entrypoint.
