### ISSUE TITLE
Move the integration tests to pytest

### ISSUE THREAD

**Issue by FFY00** [FFY00/python-build#44]
As discussed, the integration tests to make sure that common packages build successfully (https://github.com/FFY00/python-build/blob/master/.github/workflows/build.yml) should be moved to pytest. This tests should be disabled by default and enabled by passing a CLI argument. Nox/tox should run the integration tests by default(?) and allow us to opt out.

**Comment by FFY00** [comment]
@gaborbernat is it possible to make tox run the integration tests by default but allow us to opt out?

**Comment by gaborbernat** [comment]
For sure 👍

**Comment by FFY00** [comment]
This can be closed with #56 merged.
