### ISSUE TITLE
mypy run via tox/pre-commit

### ISSUE THREAD

**Issue by gaborbernat** [FFY00/python-build#48]
Should we run mypy via a tox/nox env, or via a pre-commit hook https://github.com/pre-commit/mirrors-mypy?

**Comment by FFY00** [comment]
Since it can take a while, it's probably best to not have it in pre-commit.

However I am not oposed.

**Comment by gaborbernat** [comment]
I'm happy either way but just wanted to raise the option to get a consensus.

**Comment by FFY00** [comment]
Given Paul's comment on #38, I would say we have a consensus. Feel free to reopen if you think it's needed.

> I imagine I would simply not install the pre-commit hooks if they were going to add more than 1-2 seconds to the time it takes to commit.

**Comment by gaborbernat** [comment]
So we'll keep it as separate nox target.
