### ISSUE TITLE
should github action names be lower or upper case?

### ISSUE THREAD

**Issue by gaborbernat** [FFY00/python-build#50]
I personally only make upper case content that's a paragraph and ends with a period. Github actions don't tend to end with a period so my vote is under making them lower case.

See https://github.com/FFY00/python-build/pull/49#discussion_r444978340

**Comment by FFY00** [comment]
I just explained this there but the reasoning is that the non-configurable steps in github actions default to this. If we don't capitalize it, it does not follow the style and looks bad IMO.

Example: https://github.com/FFY00/python-build/pull/49/checks?check_run_id=802831513

**Comment by gaborbernat** [comment]
🤷 whoever decided to use capital names in Github actions was not thinking about grammatical rules 🤷
