### ISSUE TITLE
Improvements to test suite

### ISSUE THREAD

**Issue by pganssle** [FFY00/python-build#55]
Opening a new issue to replace #52.

Per the discussion in #18, the current set of tests is not really adequate to give us strong confidence in the robustness of the implementation. Before actually releasing the next version, we need to improve the test suite, specifically:

- [x] Isolated builds should happen in python environments with no packages installed (not even `setuptools` and `wheel`).
- [x] We should validate the functionality both via `PYTHONPATH`, `sdist` and `wheel`.
- [x] Integration tests should live in `pytest`
- [x] We should reduce the reliance on mocks to the absolute minimum — for example avoid mocking or at least use `autospec` in [these tests](https://github.com/FFY00/python-build/blob/39166d72923648290fe12c4e0695037264c4bb3a/tests/test_projectbuilder.py#L173-L175).
- [x] End reliance on implementation details such as is happening in [this test](https://github.com/FFY00/python-build/blob/39166d72923648290fe12c4e0695037264c4bb3a/tests/test_projectbuilder.py#L179).

**Comment by FFY00** [comment]
I agree with everything.

Do you think it makes sense making `DEFAULT_BACKEND` public?

**Comment by pganssle** [comment]
> Do you think it makes sense making `DEFAULT_BACKEND` public?

My immediate thought is no, but I am surprised that you decided to expose _any_ public API for this module at all, because I don't know who the target consumers for such a thing would be. For what purpose do you envision consumers using `build` as a library? Why would they need to know what the default backend is?

I note that `_build_backend` is also not public, which makes me think that the actual backend should be expected to be an implementation detail. If that's not the case and `build_backend` is made public, then in some ways there is _less_ need for `DEFAULT_BACKEND` to be made public, since someone can get that information by constructing a `ProjectBuilder` with an empty `pyproject.toml` and querying `build_backend`.

**Comment by FFY00** [comment]
> My immediate thought is no, but I am surprised that you decided to expose _any_ public API for this module at all, because I don't know who the target consumers for such a thing would be. For what purpose do you envision consumers using `build` as a library?

There are some projects I have in my TODO list that could benefit from this. I could always just have them call the CLI directly but that isn't a great experience IMO. Since I was already going to have an internal API, I figured I would just expose it. My thought was that I would design this API and just have the CLI be a wrapper for this. I don't think many people will be interested in using python-build for the API, but there might be some users that need a handle particularly tailored use-case, mainly people dealing with custom environments. This was a big issue for me, I don't want it to be an issue for anyone else. So I am willing to put just a little bit of more work to also maintain an API.

> Why would they need to know what the default backend is?

I imagine someone might but I have no concrete example. Which probably tells us to not do it until someone asks for it, right?

**Comment by pganssle** [comment]
> I imagine someone might but I have no concrete example. Which probably tells us to not do it until someone asks for it, right?

Agreed.

**Comment by FFY00** [comment]
#85 should handle the `PYTHONPATH`, `sdist` and `wheel` validation.

#86 uses autospec everywhere possible, but note that we are already relying on mocks *much less* than before. We have a set of dummy packages that we use for the tests, see https://github.com/FFY00/python-build/tree/master/tests/packages. The current mock usage is very deliberate, we use then to avoid actually calling the PEP517 hooks and instead we validate that they are called correctly for eg.

#87 removes some internal API usages. The rest are also deliberate, for eg. `__main__._error` calls `exit()`, so we mock it and make sure it is called.

Once they are merged, I think we are ready to close this and make a release. Let me know what you think.

**Comment by FFY00** [comment]
Everything is merged, as soon as I get your feddback, we can proceed :blush:

**Comment by pganssle** [comment]
I think this is definitely sufficient for a release, though I'm not sure where this one is addressed:

> * Isolated builds should happen in python environments with no packages installed (not even `setuptools` and `wheel`).

It seems like the tests have a hard dependency on `setuptools`, which might bite us in the future, but I'd rather not let the perfect be the enemy of the good here.

:shipit:

**Comment by FFY00** [comment]
Well, unless `ensurepip` is installing `setuptools` or `wheel`, they shouldn't be there. I was under the impression `ensurepip` would bootstrap a `pip` installation with all dependencies vendored.

**Comment by FFY00** [comment]
Just checked, setup

```ipython
In [1]: import build.env

In [2]: import subprocess

In [3]: with build.env.IsolatedEnvironment.for_current():
   ...:     print(subprocess.check_call(['/usr/bin/python', '-c', 'import setuptools']))
   ...:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-3-cd5661b60f05> in <module>
      1 with build.env.IsolatedEnvironment.for_current():
----> 2     print(subprocess.check_call(['/usr/bin/python', '-c', 'import setuptools']))
      3

/usr/lib/python3.8/subprocess.py in check_call(*popenargs, **kwargs)
    362         if cmd is None:
    363             cmd = popenargs[0]
--> 364         raise CalledProcessError(retcode, cmd)
    365     return 0
    366

CalledProcessError: Command '['/usr/bin/python', '-c', 'import setuptools']' returned non-zero exit status 1.
```

Same after using `env.install`, which will can `ensurepip` and use pip to install some requirements into the environment.

```ipython
In [4]: with build.env.IsolatedEnvironment.for_current() as env:
   ...:     env.install(['tzdata'])
   ...:     print(subprocess.check_call(['/usr/bin/python', '-c', 'import setuptools']))
   ...:
Looking in links: /tmp/tmpltg6k1cw
Requirement already satisfied: setuptools in /home/anubis/.virtualenvs/python-build/lib/python3.8/site-packages (47.1.1)
Requirement already satisfied: pip in /home/anubis/.virtualenvs/python-build/lib/python3.8/site-packages (20.1.1)
Collecting tzdata
  Downloading tzdata-2020.1-py2.py3-none-any.whl (337 kB)
     |████████████████████████████████| 337 kB 663 kB/s
Installing collected packages: tzdata
Successfully installed tzdata
WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
You should consider upgrading via the '/home/anubis/.virtualenvs/python-build/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'
```

**Comment by FFY00** [comment]
I will make a new release now.

**Comment by pganssle** [comment]
Yeah, sorry, I didn't look too closely into it, I was just reacting to [`setuptools`'s presence in the `requirements-dev.txt` file](https://github.com/FFY00/python-build/blob/2b51c7361590fcede5a96dde6f8a366bd9a6ecc0/requirements-dev.txt#L12).
