### ISSUE TITLE
Relicense to the Hippocratic License

### ISSUE THREAD

**Issue by FFY00** [FFY00/python-build#62]
The Hippocratic License is a permissive license, just like MIT, but enforces the licensee to adhere to human rights principles and laws. This might seem a bit silly but with open software being more widely used, I want to make sure my software takes no part in helping out organizations that violate human rights, such as ICE.

https://firstdonoharm.dev
https://ethicalsource.dev

@felixonmars @gaborbernat @pganssle do you guys agree to relicense your contributions under the Hippocratic License 2.1?

**Comment by felixonmars** [comment]
It is a non-free license, which means distributions like Arch and Debian will exclude the software from their repositories, and the whole free software world will need to avoid this project. Please reconsider this.

**Comment by pganssle** [comment]
You absolutely do not have my permission to relicense my contributions. Please do not adopt a dodgy proprietary license like this. I think adopting this license would also make me change my vote for including this in the PyPA from +1 to strong -1, since this would make widespread adoption effectively impossible among anyone who cares about license compliance.

**Comment by FFY00** [comment]
> It is a non-free license, which means distributions like Arch and Debian will exclude the software from their repositories, and the whole free software world will need to avoid this project. Please reconsider this.

I am not a lawyer, but how is this a non-free license?

> You absolutely do not have my permission to relicense my contributions. Please do not adopt a dodgy proprietary license like this. I think adopting this license would also make me change my vote for including this in the PyPA from +1 to strong -1, since this would make widespread adoption effectively impossible among anyone who cares about license compliance.

I don't want to start an argument, but I think calling a "dodgy proprietary license" is a bit unfair. As I said I am not a laywer, so maybe I am being naive, what is essentially wrong with this license? I will accept your claims of it blocking widespread adoption as I do not really have any way to argue that. As such, I agree that it would not make sense to have the project in PyPA so I am gonna drop it.

**Comment by felixonmars** [comment]
> > It is a non-free license, which means distributions like Arch and Debian will exclude the software from their repositories, and the whole free software world will need to avoid this project. Please reconsider this.
> 
> I am not a lawyer, but how is this a non-free license?

Referring to https://www.gnu.org/licenses/license-list.en.html#hippocratic (listing in the "Nonfree Software Licenses" section):

```
This is not a free software license, because it restricts what jobs users can use the software for. That denies freedom 0. This entry was previously listed as the First Do No Harm license.
```

An extended explanation can also be found here: https://www.fsf.org/blogs/licensing/a-roundup-of-recent-updates-to-our-licensing-materials-november-2019-to-april-2020

**Comment by pganssle** [comment]
> I am not a lawyer, but how is this a non-free license?

It has discrimination against [fields of endeavor](https://opensource.org/osd) (point 6).

> I don't want to start an argument, but I think calling a "dodgy proprietary license" is a bit unfair. As I said I am not a lawyer, so maybe I am being naive, what is essentially wrong with this license?

Generally speaking, these sorts of things are proprietary because they're not open / free / libre, and they're dodgy because writing something like this is *super hard* and likely not even possible. Most of the OSS lawyer types I've seen have basically said, "This is a fool's errand, try to address these problems in a different way." Here is [an article from Bruce Parens on ethical licenses.](https://perens.com/2019/10/12/invasion-of-the-ethical-licenses/)

**Comment by FFY00** [comment]
> Referring to [gnu.org/licenses/license-list.en.html#hippocratic](https://www.gnu.org/licenses/license-list.en.html#hippocratic) (listing in the "Nonfree Software Licenses" section):
> 
> ```
> This is not a free software license, because it restricts what jobs users can use the software for. That denies freedom 0. This entry was previously listed as the First Do No Harm license.
> ```
> 
> An extended explanation can also be found here: [fsf.org/blogs/licensing/a-roundup-of-recent-updates-to-our-licensing-materials-november-2019-to-april-2020](https://www.fsf.org/blogs/licensing/a-roundup-of-recent-updates-to-our-licensing-materials-november-2019-to-april-2020)

> It has discrimination against [fields of endeavor](https://opensource.org/osd) (point 6).

I totally agree with that, but that refers to the 1.1 version. I was proposing version 2.1, it changed from restricting access to asking for compliance to human rights principals and laws. From my understanding, you are free to do whatever you want with the software, there is no discrimination, but you have to comply with certain requirements. This requirements are applied to everyone equally, so my interpretation here is that version 2.1 does not violate none of OSI requirements and is definitely a free license, but again, I am not a laywer.

> Generally speaking, these sorts of things are proprietary because they're not open / free / libre, and they're dodgy because writing something like this is _super hard_ and likely not even possible.

Well, I would not label it "dodgy" but it's just my opinion. Anyway, there is no point arguing this right now.
