### ISSUE TITLE
Would the Python API be supported?

### ISSUE THREAD

**Issue by uranusjr** [FFY00/python-build#63]
I’m thinking about creating a generic package builder that supports both PEP 517 and legacy projects. But I want to be able to run the builder “out of band” i.e. the package may be built against a different interpreter than the one running the tool. Both `PackageBuilder` and `IsolatedEnvironment` seem to be very well implemented and modulised (much kudos) to make this possible, and my plan is to subclass and override limited parts of them. But would this be a supported usage going forward, or should I expect things to break (like pip’s implementation)?

**Comment by FFY00** [comment]
Yes, it is public API so you can rely on it. This was exactly my goal when designing.

**Comment by uranusjr** [comment]
Thanks! I’ll try it out and report back if anything is missing.

**Comment by FFY00** [comment]
Please do :grin:! Just be aware that `IsolatedEnvironment` is unreleased, although I don't think we will need to change the public API. It currently can't handle environment markers, #61 should fix it.

**Comment by uranusjr** [comment]
I am aware, thanks. And `install` is one of the functions I need to override anyway, so the environment marker issue is not a problem for me 😛
