### ISSUE TITLE
Backport the `--no-isolation` flag

### ISSUE THREAD

**Issue by FFY00** [FFY00/python-build#66]
I want to propose the adoption of python-build for Arch Linux packaging and to avoid breaking things due the default behavior (build in isolation) change in the new version, I propose tagging a 0.0.3.2 release which would be just 0.0.3.1 with a patch to enable the use of the `--no-isolation`/`-n` flag.

This way we can write `python -m build --no-isolation` in our build instructions and not have to change it when the default behavior changes.

cc @pganssle @gaborbernat

**Comment by gaborbernat** [comment]
Sure 🤷‍♂️

**Comment by FFY00** [comment]
Not relevant anymore.
