### ISSUE TITLE
Command does not change the current directory to project root

### ISSUE THREAD

**Issue by uranusjr** [FFY00/python-build#68]
PEP 517 mandates “all hooks are run with working directory set to the root of the source tree”. This is important for in-tree hooks since the cwd is relied on to find the PEP 517 modules.

This fails:

```
$ python -m build ./example-project -s -o .
ERROR Backend 'pep517' is not available
```

But this works:

```
$ cd example-project
$ python -m build -s -o .
$ ls *.tar.gz
my_package-2.tar.gz
```

**Comment by FFY00** [comment]
Can you confirm this is working on `master`?

**Comment by uranusjr** [comment]
The directory change works now, thanks! The change however causes a side effect on the `-o` option:

```
$ python -m build ./example-project -s -o .
$ ls
example-project
$ ls example-project
example_project-1.0.tar.gz
pyproject.toml
```

The output directory is resolved against the project root, but I’d expect it to be resolved against the initial working directory instead.

**Comment by FFY00** [comment]
Okay, closing this but keeping the other issue open.
