### ISSUE TITLE
Missing backend error when PEP 518 requirements are not already satisfied

### ISSUE THREAD

**Issue by pganssle** [FFY00/python-build#98]
Using `build==0.0.4`, it appears that the `python-build` command must be activated in an environment where the build backend is already installed! As an example, creating a project with a `pyproject.toml` like this:

```toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
```
Then `touch setup.cfg`, and create a virtualenv like so:

```
virtualenv venv --no-setuptools --no-wheel
source venv/bin/activate
pip install build==0.0.4
```

Now when you invoke `python-build -w .`, you'll get:

```
$ python-build .
ERROR Backend 'setuptools.build_meta' is not available
```

I think the issue is that [`ProjectBuilder` checks the existence of the build backend](https://github.com/FFY00/python-build/blob/3d2491fb33abbcfd8ce514939668823bf0235dac/src/build/__init__.py#L160-L164), but in `__main__` it is [constructed before the environment is built](https://github.com/FFY00/python-build/blob/3d2491fb33abbcfd8ce514939668823bf0235dac/src/build/__main__.py#L77-L82).

I'll note that you can build a wheel just fine from an environment where `setuptools` but not `wheel` is installed, but if `setuptools` isn't installed ahead of time, it will cause problems.

This problem is related to but distinct from #97.

I think this definitely needs an integration test.

**Comment by FFY00** [comment]
I think we should move that check to `build`.
